# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Solitude
subtitle: '一个简洁优雅的 Hexo 主题'
description: 一个简洁优雅的 Hexo 主题，支持懒加载、PWA、Latex 和多种评论系统。
keywords: 'Ever Fu,Solitude'
author: Ever Fu
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://solitude.js.org/preview/zh
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: preview-zh
public_dir: docs/.vitepress/dist/preview/zh/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:
  - preview/zh

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solitude
theme_config:
  site:
    name:
      class: text
      custom: Solitude
    # 网页icon
    # Web icon
    icon: https://s3.qjqq.cn/47/66c2b219a226f.png!color

  nav:
    menu:
      文库: # 显示名称 / Display name
        归档: /archives/ || fas fa-folder-closed # 子菜单名称：路径 || 图标 / Submenu name: path || icon
        分类: /categories/ || fas fa-clone
        标签: /tags/ || fas fa-tags
      友链:
        友情链接: /links/ || fas fa-user-group
        宝藏博主: javascript:travelling() || fas fa-gift
      关于: /about/

    right:
      random: true # 随机文章跳转 / random post button
      custom:
        - name: English
          url: /
          icon: fas fa-language

  hometop:
    enable: true # 是否打开 / if enable
    # banner display
    banner:
      # 左上角显示大文字
      # Large text displayed in the upper left corner
      # tip：可使用html标签
      # tip: html tags be used
      title: 宁静致远 <br>热爱生活
      # 左上角显示小文字
      # Small text displayed in the upper left corner
      url: Hexo Theme Solitude
      # 轮播icon
      # Carousel icon
      # tip: 76x76 size
      icon:
        HTML: # 名字 / Name
          img: https://s3.qjqq.cn/47/66c2a95ed3cb3.png!color # 图片 / Image
          color: "#E14E1D" # 背景色 / Background color
        JS:
          img: https://s3.qjqq.cn/47/66c2a97c62826.png!color
          color: "#F0DB50"
        Docker:
          img: https://s3.qjqq.cn/47/66c2a9a40c1c7.png!color
          color: "#2496EE"
        Flutter:
          img: https://s3.qjqq.cn/47/66c2a9c318057.png!color
          color: "#252938"
        WebPack:
          img: https://s3.qjqq.cn/47/66c2a9e5ecfb4.png!color
          color: "#252938"
        Git:
          img: https://s3.qjqq.cn/47/66c2aa0398240.png!color
          color: "#F13C2E"

    # 左下跳转按钮
    # Banner lower left jump button
    group:
      Course: /categories/教程/ || fas fa-book || linear-gradient(to right,#358bff,#15c6ff)

    # 右侧置顶列表（在文章的front matter中添加“recommend: true”）
    # Right top list (add "recommend: true" in the front matter of the article)
    recommendList:
      # 左上角显示文字
      # Large text displayed in the upper left corner
      sup: Top
      # 左下角大字
      # Large text in the lower left corner
      title: Solitude 文档
      # 点击跳转链接
      # Click the jump link
      url: https://solitude.js.org/
      # 显示背景图片
      # Display background image
      img: https://s3.qjqq.cn/47/66c2b25979b09.png!color
      # 阴影颜色
      # Shadow color
      color: "none"

  aside:
    home:
      noSticky: "about"
      Sticky: "allInfo"
    post:
      noSticky: "about"
      Sticky: "newestPost"
    page:
      noSticky: "about"
      Sticky: "newestPost,allInfo"
    position: 1
    card:
      style: 1
      author:
        img: https://github.com/everfu.png
        sticker:
      url: /about/
      content: Share new knowledge and record the moments of life.
      content2: This site is powered by Hexo and has the theme of Solitude.
      sayhello: # 样式为2时无效
        morning: ✨ Good morning. It's a new day
        noon: It's time for a midday break
        afternoon: Tea time. 🍵
        night: early bedtime
        goodnight: Good night 😴
      sayhello2: # 样式为2时无效
        - You'll make it.
        - You're gonna make it.
        - Good luck, stranger.
      information: # 样式为1时请不要超过4个
        Github: https://github.com/everfu || fab fa-github
        Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili

    toc:
      post: true
      page: false
      vague: true

    tags:
      enable: true
      limit: 20
      highlight_list:
      #  - Hexo

    archive:
      enable: true
      # 显示类型
      type: "month" # month: 按月 / year: 按年 : month: by month / year: by year

    # 建站信息
    # Website information
    siteinfo:
      # 文章数
      # Number of articles
      postcount: true
      # 总字数
      # The number of words on the web site
      wordcount: true
      # 访问量
      # PV
      pv: true
      # 访客数
      # UV
      uv: true
      # 最后更新日期
      # Last update date
      updatetime: false
      # 建站时间
      # Website creation time
      runtimeenable: true
      # 格式：yyyy-MM-dd hh-mm-ss
      # Format: yyyy-MM-dd hh-mm-ss
      runtime: "2023-04-20 00:00:00"

  # 首页文章配置信息
  # Configure information on the home page
  index_post_list:
    direction: row # row / column
    column: 2 #2:2列 3:3列
    content: 2 # 1: post.description / 2: 自动获取description或截取内容(Automatically get descriptions or screenshots) / 3: 只使用截取内容(Use only screenshots) / false: 不显示内容(No content is displayed)
    length: 200 # 截取内容的长度 : The length of the screenshot content
    cover: both # left: 在左侧 : left / right: 在右侧 : right / both: 两侧 : both

  # 页面默认设置
  # page default settings
  page:
    error: true # 404页面 / 404 page
    tags: true # 标签页 /  Tags page
    categories: true # 分类页 /  Categories page
    default: # 默认值 /  Default value
      # 默认图片
      # default cover
      cover:
      # - /img/default.avif # 默认图片 / default cover

  says:
    enable: true
    home_mini: true
    style: 1
    strip: 30

  # 文章页默认设置
  # post default settings
  post:
    default:
      # 文章默认图片
      # default cover
      cover:
      # -  # 默认图片 / default cover
      # 文章发布默认地址
      # default post locate
      locate: China
      # 文章默认版权
      # default post copyright
      copyright:
        enable: true
        author:
          url: /about/ # 点击头像跳转地址
          img: # 显示头像，不填写默认显示site_icon
        license: CC BY-NC-SA 4.0
        licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
    # 顶部文章简介
    # Top article introduction
    meta:
      date: true # 发布日期 / Release date
      updated: true # 更新日期 / Update date
      locate: false # 位置 / Location
      wordcount: true # 字数 / Number of words
      readtime: true # 访问 / uv
      pv: true # 浏览量 / pv
      comment: false # 评论数 / Comment count
    # 打赏
    # reward
    award:
      enable: true
      appreciators: /about # 赞赏记录 / Appreciative records
      title: 感谢您的赞赏
      desc: 因为您的支持，我才意识到写文章的价值
      list:
        - name: 微信
          qcode: https://s3.qjqq.cn/47/66c2b322adbd3.png!color
          url: https://s3.qjqq.cn/47/66c2b322adbd3.png!color
          color: "#7bbd3f"
        - name: 支付宝
          qcode: https://s3.qjqq.cn/47/66c2b37d1aa6e.png!color
          url: https://s3.qjqq.cn/47/66c2b37d1aa6e.png!color
          color: "#1C8BFF"
    # 分享按钮，需要是什么哪些按钮，填写后开启
    share:
      enable: true
      list:
        - qq
        - weibo
        - twitter
        - facebook
        - telegram
        - whatsapp
        - linkedin
        - link
        - qrcode
    # 版权中订阅按钮跳转链接，填写地址后开启
    # Subscription button jump link in copyright
    rss: /atom.xml
    covercolor:
      enable: true
      mode: api # local：本地取色 / api：img2color取色 : local: local color / api: img2color color
      api: https://img2color-efu.vercel.app/api?img= # api地址 / api address
      time: 43200000 # api取色间隔（毫秒），默认为12小时 / api color interval (milliseconds), default is 12 hours
    footer:
      enable: true
      desc: From Ever Fu's article.
      button: # 跳转按钮
        enable: false
        name: More
        url: /about/

  # Custom Theme Color
  theme_color:
    dark: "#8f4dcc" # Dark mode
    dark_op: "#f2b94b23" # Dark mode transparent
    dark_op_deep: "#f2b94bdd" # Dark mode transparent dark
    dark_none: "#f2b94b00" # Dark mode transparent colorless
    light: "#425AEF" # Light mode
    light_op: "#4259ef23" # Light mode transparent
    light_op_deep: "#4259efdd" # Light mode transparent dark
    light_none: "#4259ef01" # Light mode transparent colorless

  display_mode:
    type: auto
    universe: true

  footer:
    information:
      author: false
      left:
        Github: https://github.com/everfu || fab fa-github
        Email: mailto:o@efu.me || fas fa-envelope
      right:
        Bilibili: https://space.bilibili.com/1329819902 ||  fab fa-bilibili
        Douyin: https://v.douyin.com/iJsLc8jt/ || fab fa-tiktok

    group:
      Project:
        Document: https://solitude.js.org
        Github: https://github.com/everfu/hexo-theme-solitude
      Sponsor:
        Patreon: https://www.patreon.com/everfu
        Polar: https://polar.sh/everfu
    randomlink: true
    links:
      - name: Theme
        url: https://github.com/everfu/hexo-theme-solitude
      - name: RSS
        url: /atom.xml

  errorpage:
    img: /img/404.avif
    text: 404 Not Found
    recommendList: true

  copy:
    enable: true
    copyright:
      enable: false
      limit: 50 # word count. （字数）

  # 懒加载
  # lazyload
  lazyload:
    enable: true
    field: site # post, site
    placeholder: /img/loading.avif
    errorimg: /img/error_load.avif

  loading:
    fullpage: true
    pace: true

  highlight:
    enable: true
    limit: 200 # 代码行高限制 / Code line limit
    copy: true # 是否开启复制按钮 / Whether to enable the copy button
    expand: true # 是否默认展开 / Whether to expand by default
    theme: mac # default: 默认 / mac : apple terminal
    color: default # default: 默认  / solidity: solidity / dracula: dracula

  lightbox: true
  fancybox: true
  mediumZoom: false

  mermaid: true

  OpenGraph:
    enable: true
    options:
    #  twitter_card:
    #  twitter_image:
    #  twitter_id:
    #  twitter_site:
    #  google_plus:
    #  fb_admins:
    #  fb_app_id:

  wordcount: true
  busuanzi: true
  busuanzi_use: 0 # 0: 原版 / 1: 青秸(other: 其它自定義的busuanzi平台)

  search:
    enable: true
    type: local
    tags:
      - Solitude
    algolia:
    # hits:
    #   per_page: 6
    local:
      preload: false
      CDN: /preview/zh/search.xml

  katex:
    enable: true
    per_page: true # 是否在每页都加载 / Whether to load on each page
    copytex: true # 是否开启复制公式 / Whether to enable copy formula

  console:
    enable: true
    recentComment:
      enable: true
      storage: .2
    card:
      tags: true
      archive: true

  extends:
    head: # 在head中插入 / Insert in head
    # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
    body: # 在body中插入 / Insert in body

  pwa:
    enable: false
    manifest: /manifest.json # manifest.json 文件路径
    theme_color: "#006a73" # 主题颜色
    mask_icon: /img/pwa/favicon.ico # 遮罩图标
    apple_touch_icon: /img/pwa/favicon.ico # 苹果触摸图标
    bookmark_icon: /img/pwa/favicon.ico # 书签图标
    favicon_32_32: /img/pwa/favicon_32.ico # 32x32图标
    favicon_16_16: /img/pwa/favicon_16.ico # 16x16图标

  #background:
  #  enable: true
  #  opacity: .2
  #  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  #  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg

  right_menu:
    enable: true
    custom_list:
      - name: Random
        click: toRandomPost()
        id: menu-randomPost
        class:
        icon: fas fa-random
      - name: Categories
        click: pjax.loadUrl('/categories/') # 外链用 window.open，pjax 无法请求跨域内容
        id:
        class:
        icon: fas fa-clone
      - name: Tags
        click: pjax.loadUrl('/tags/')
        id:
        class:
        icon: fas fa-tags

  expire:
    enable: true
    time: 30 # days
    position: top # top / bottom
    text_prev: '这篇文章已经过期'
    text_next: '，如果内容不符，请联系我'

  CDN:
    internal: custom
    third_party: custom
    version: true
    custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
    option:
      busuanzi_js: https://vercount.one/js

# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default)
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: true  #true(default)
    depth:        #3(default)
    over_write: false
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.

search:
  path: search.xml
  field: post
  content: true
  format: html

nofollow:
  enable: true
  field: site
  exclude:
    - 'exclude1.com'
    - 'exclude2.com'
